---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
library(shinydashboard)
library(DT)
library(shinythemes)
library(formattable)
library(reactable)
library(kableExtra)
library(shinyjs)
library(tidyselect)
library(dplyr)
library(lubridate)
library(reshape2)
library(ggplot2)
library(rsconnect)
library(shiny)
library(flexdashboard)
library(tidyverse)
library(shinythemes)
library(shinyBS)
library(reactable)
library(lubridate)
library(dygraphs)
library(xts)
```

```{r include=FALSE}
Data <- read.csv("sales 22.07.2023.csv")

Targets <- read.csv("Targets.csv")
# convert the date column from character to date format
Data$TRNS.DATE <- as.Date(Data$TRNS.DATE, "%m/%d/%Y")
Data$BRANCH <- as.factor(Data$BRANCH)
Data$CUSTOMER <- as.factor(Data$CUSTOMER)
Data$BRAND <- as.factor(Data$BRAND)

#Removing Unwanted Rows

Data <- Data %>% select(1,6,7,9,10,11,12,13,15,23)



# Subset the data based on the Each Individual Sales Rep.
Beatrice <- subset(Data, SALES.REP == "Beatrice ")
Doris <- subset(Data, SALES.REP == "Doris")
Regina  <- subset(Data, SALES.REP == "Regina ")
Wanyonyi <- subset(Data, SALES.REP == "Wanyonyi")
Colleta  <- subset(Data, SALES.REP == "Colleta ")
Richard <- Data[grepl("Richard|richard", Data$SALES.REP), ]
Walter <- Data[grepl("Walter|WALTER|walter", Data$SALES.REP), ]
Monicah <- subset(Data, SALES.REP == "Monicah")
HQ <- subset(Data, SALES.REP == "HQ")
Unilever <- Data[grepl("HELLMANN'S|KNORR SOUP|ROBS|KNORR AROMAT|SUNLIGHT|OMO|KNORR DRESSING|COMFORT|PEPSODENT|KNORROX",Data$BRAND), ]


```

```{r}
ui <- dashboardPage(
  dashboardHeader(title = "On Demand",
                  dropdownMenuOutput("messageMenu"),
                   titleWidth = 300
                  ),
  
  dashboardSidebar(
    sidebarMenu(
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Targets", tabName = "Targets", icon = icon("th")),
      menuItem(" Weekly_Performance", tabName = "Weekly_Performance", icon = icon("th")),
      menuItem("Sales_Forecast", tabName = "Sales_Forecast", icon = icon("th")),
      menuItem("Regina", tabName = "Regina", icon = icon("user")),
      menuItem("Beatrice", tabName = "Beatrice", icon = icon("user")),
      menuItem("Richard", tabName = "Richard", icon = icon("user")),
      menuItem("Wanyonyi", tabName = "Wanyonyi", icon = icon("user")),
      menuItem("Colleta", tabName = "Colleta", icon = icon("user")),
      menuItem("Walter", tabName = "Walter", icon = icon("user")),
      menuItem("unilever", tabName = "unilever", icon = icon("user"))

    )
  ),
  
  ## Body content
  
  dashboardBody(
    tabItems(
      # First tab content
      tabItem(tabName = "dashboard",
              fluidPage(
              fluidRow(
                box(dygraphOutput("PlotData", height = 250)),
                infoBox("Last Update", "07/07/2023" , icon = icon("credit-card"), fill = TRUE, width = 6),
                # Dynamic infoBoxes
                box(plotOutput("OverallBar", height = 250)),
             ),
                   h2("Overall Performance"),
              DTOutput("Data_total"),
              h2("Accounts Performance"),
              DTOutput("Data_SalesRepwide"),
             h2("Brand Performance"),
              DTOutput("Overall_Brandwide"),
            )
      ),
      # Third tab content
      tabItem(tabName = "Targets",
              h2("Accounts Targets"),
              DTOutput("Targets")
              
      ),
      # Forth tab content
      tabItem(tabName = "Weekly_Performance",
              fluidRow(),
              fluidPage(
                    h2("Weekly Performance"),
              DTOutput("Weekly_SalesRepwide"),
              )
      ),
      # Fifth tab content
      tabItem(tabName = "Sales_Forecast",
              h2("Sales Rep Performance Per Store")
      ),
      # Sixth tab content
      tabItem(tabName = "Regina",
              h2("Regina"),
              fluidPage(
              fluidRow(
              box(dygraphOutput("PlotRegina", height = 250),width = 8),
              infoBox(strong("Total June Sales, 47% Achievement "), 1705450.8	 , icon = icon("credit-card"), fill = TRUE, width = 4),
              box(plotOutput("plot11", height = 250), width = 4)),
                 h2("Monthly Performance"),
              DTOutput("Regina_monthlywide"),
                 h2("Account Contribution"),
              DTOutput("Regina_wide"),
               h2("Account Performance"),
              DTOutput("Regina_Customerwide"),
                h2("Brand Performance"),
              DTOutput("Regina_Brandwide"),
               h2("Branch Performance"),
              DTOutput("Regina_branchWide")
              )
      ),
      # Seventh tab content
      tabItem(tabName = "Beatrice",
              h2("Beatrice"),
             fluidPage(tags$head(
                                    tags$style(
                                      HTML("
                                        h2 {
                                          font-weight: bold;
                                          text-align: center;
                                        }
                                      ")
                                    )
                                  ),
             box(dygraphOutput("PlotBeatrice", height = 250),width = 8),
             fluidRow( box(plotOutput("plot10", height = 150),width = 4)),
             h2("Monthly Performance"),
              DTOutput("Beatrice_monthlywide"),
             h2("Account Contribution"),
              DTOutput("Beatrice_wide"),
              h2("Account Performance"),
              DTOutput("Beatrice_Customerwide"),
              h2("Brand Performance"),
              DTOutput("Beatrice_Brandwide"),
             h2("Branch Performance"),
              DTOutput("Beatrice_branchWide")
              )
                  ),
      # Eight tab content
      tabItem(tabName = "Richard",
              h2("Richard"),
            fluidRow(box(dygraphOutput("PlotRichard", height = 250),width = 8),
                     infoBox("Total June Sales", 44162.70 , icon = icon("credit-card"), fill = TRUE, width = 4)),
              fluidPage(
                box(plotOutput("RichardBar", height = 450), width = 600),
                h2("Monthly Performance"),
               DTOutput("Richard_total"),
               h2("Account Performance"),
               DTOutput("Richard_CustoRmerwide"),
                 h2("Brand Performance"),
              DTOutput("Richard_Brandwide")
              )
      ),
      # Nineth tab content
      tabItem(tabName = "Wanyonyi",
              h2("Wanyonyi"),
            fluidRow(box(dygraphOutput("PlotWanyonyi", height = 250),width = 8),
                    infoBox("Total June Sales", 2706009.42	 , icon = icon("credit-card"), fill = TRUE, width = 4)),
             fluidPage(
               box(plotOutput("plotWanyonyi", height = 250),width = 600),
               h2("Monthly Performance"),
               DTOutput("Wanyonyi_total"),
                 h2("Account Performance"),
               DTOutput("Wanyonyi_Customerwide"),
                 h2("Brand Performance"),
              DTOutput("Wanyonyi_Brandwide"),
                 h2("Store Performance"),
               DTOutput("Wanyonyi_wide"),
               
             )
      ),
      # Tenth tab content
      tabItem(tabName = "Colleta",
              box(plotOutput("plot6", height = 250), width = 600),
             h2("Monthly Performance"),
               DTOutput("Colleta_totals"),
              h2("Account Performance"),
              DTOutput("Colleta_Customerwide"),
              h2("Brand Performance"),
              DTOutput("Colleta_Brandwide"),
              h2("Branch Performance"),
              DTOutput("Colleta_branchWide"),
      ),
      # Tenth tab content
      tabItem(tabName = "Walter",
              h4("Walter"),
               box(dygraphOutput("PlotWalter", height = 250)),
             fluidPage(
               DTOutput("Walter_total"),
                h2("Brand Performance"),
              DTOutput("Walter_Brandwide"),
             )
             ),
      tabItem(tabName = "unilever",
             fluidPage(
                h2("Performance"),  
                DTOutput("UnileverSales"),
                h2("Accounts Performance"), 
               selectInput("rep_filter", "Sales Rep:", choices = c("All",
                                                                   "Beatrice ",
                                                                   "Regina ",
                                                                   "Wanyonyi",
                                                                   "walter")),
               DT::dataTableOutput("UnileverProd"),
                h2("Beatrice Brand Performance"),  
                selectInput("acc_filter", "Sales Rep:", choices = c("All",
                                                                    "Majid Al Futtaim",
                                                                    "Chandarana Supermarket Ltd",
                                                                    "CLEANSHELF SUPERMARKETS LTD",
                                                                    "Quick Mart Ltd",
                                                                    "ONN THE WAY",
                                                                    "SKY MART ENTERPRISES LTD",
                                                                    "Karen Provision Stores Ltd")),
                 DT::dataTableOutput("UnileverBeatrice"),
                 h2("Regina Brand Performance"),  
                DTOutput("UnileverRegina"),
                h2("Wanyonyi Brand Performance"),  
                DTOutput("UnileverWanyonyi"),
             )
      )
    )
  )

)


server <- function(input, output) {
 
    output$plot6 <- renderPlot({
  plot(PlotColleta)
  })
   output$plot10 <- renderPlot({
  plot(BeatriceBar)
  })
   #Regina Horizontal Plot
  output$plot11 <- renderPlot({
  plot(ReginaBar)
  })
  #Richard Horizontal Plot
  output$RichardBar <- renderPlot({
  plot(RichardBar)
  })
   #Wanyonyi Horizontal Plot
  output$plotWanyonyi <- renderPlot({
  plot(WanyonyiBar)
  })
  
      #Sales Horizontal Plot
  output$OverallBar <- renderPlot({
  plot(OverallBar)
  })
  
    # Targets table
    output$Targets <- renderDT({
    Targets %>% select(1,9)
  }, options = list(pageLength = 20, scrollX = TRUE,
                    rownames = FALSE ))
  
   
    # Render Beatrice's table
  output$Beatrice_wide <- renderDT({
    Beatrice_wide 
  }, options = list(pageLength = 8, scrollX = TRUE,
                    rownames = FALSE ))
 output$Beatrice_branchWide <- renderDT({
    Beatrice_branchWide
  }, options = list(pageLength = 100, scrollX = TRUE,
                    rownames = FALSE ))
   output$Beatrice_Customerwide <- renderDT({
    Beatrice_Customerwide
  }, options = list(pageLength = 8, scrollX = TRUE,
                    rownames = FALSE ))
   output$Beatrice_Brandwide <- renderDT({
    Beatrice_Brandwide
  }, options = list(pageLength = 11, scrollX = TRUE,
                    rownames = FALSE ))
    output$Beatrice_monthlywide <- renderDT({
    Beatrice_monthlywide
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
  output$PlotBeatrice <- renderDygraph({
    PlotBeatrice
  })
     # Render Regina's table
  output$Regina_monthlywide <- renderDT({
    Regina_monthlywide 
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
   output$Regina_wide <- renderDT({
    Regina_wide 
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
   output$Regina_branchWide <- renderDT({
    Regina_branchWide 
  }, options = list(pageLength = 40, scrollX = TRUE,
                    rownames = FALSE ))
   
    output$Regina_Customerwide <- renderDT({
    Regina_Customerwide 
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = TRUE ))
      output$Regina_Brandwide <- renderDT({
    Regina_Brandwide
  }, options = list(pageLength = 11, scrollX = TRUE,
                    rownames = FALSE ))
  output$PlotRegina <- renderDygraph({
    PlotRegina
  })   
 
      
        # Render Richard's table

  output$Richard_total <- renderDT({
    Richard_total
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
   output$Richard_CustoRmerwide <- renderDT({
    Richard_CustoRmerwide 
  }, options = list(pageLength = 6, scrollX = TRUE,
                    rownames = FALSE ))
     output$Richard_Brandwide <- renderDT({
    Richard_Brandwide
  }, options = list(pageLength = 19, scrollX = TRUE,
                    rownames = FALSE ))
 output$PlotRichard <- renderDygraph({
    PlotRichard
   })
 
   
   # Render Wanyonyi's table
  output$Wanyonyi_wide <- renderDT({
    Wanyonyi_wide 
  }, options = list(pageLength = 4, scrollX = TRUE,
                    rownames = FALSE ))
   output$Wanyonyi_total <- renderDT({
    Wanyonyi_total
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
       output$Wanyonyi_Customerwide <- renderDT({
    Wanyonyi_Customerwide
  }, options = list(pageLength = 3, scrollX = TRUE,
                    rownames = FALSE ))
   
          output$Wanyonyi_Brandwide <- renderDT({
    Wanyonyi_Brandwide
  }, options = list(pageLength = 10, scrollX = TRUE,
                    rownames = FALSE ))
       
  output$PlotWanyonyi <- renderDygraph({
    PlotWanyonyi})      
       
   
      # Render Walter's table
  output$Walter_total <- renderDT({
    Walter_total 
  }, options = list(pageLength = 10, scrollX = TRUE,
                    rownames = FALSE ))
  
     output$Walter_Brandwide <- renderDT({
    Walter_Brandwide
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
     output$PlotWalter <- renderDygraph({
    PlotWalter
  })
  
  
      # Render Sales's table
  output$Data_total <- renderDT({
    Data_total 
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
   output$Overall_Brandwide <- renderDT({
    Overall_Brandwide
  }, options = list(pageLength = 21, scrollX = TRUE,
                    rownames = FALSE ))
     output$Data_SalesRepwide <- renderDT({
    Data_SalesRepwide
  }, options = list(pageLength = 6, scrollX = TRUE,
                    rownames = FALSE ))
   output$PlotData <- renderDygraph({
    PlotData
  })
  
  
        # Render Colleta's table
  output$Colleta_totals <- renderDT({
   Colleta_totals
  }, options = list(pageLength = 5, scrollX = TRUE,
                    rownames = FALSE ))
     
  output$Colleta_Customerwide <- renderDT({
   Colleta_Customerwide
  }, options = list(pageLength = 7, scrollX = TRUE,
                    rownames = FALSE ))
  output$Colleta_Brandwide <- renderDT({
   Colleta_Brandwide
  }, options = list(pageLength = 8, scrollX = TRUE,
                    rownames = FALSE ))
  
  output$Colleta_branchWide <- renderDT({
   Colleta_branchWide
  }, options = list(pageLength = 50, scrollX = TRUE,
                    rownames = FALSE ))
  
  
        # Render Weekly's table
  output$Weekly_SalesRepwide <- renderDT({
    Weekly_SalesRepwide 
  }, options = list(pageLength = 8, scrollX = TRUE,
                rownames = FALSE ))
     
  
  
        # Render Weekly's table
  output$UnileverProd<- renderDT({
    UnileverProd 
  }, options = list(pageLength = 10, scrollX = TRUE,
                rownames = FALSE ))
     # Filtered data based on inputs
  filtered_data <- reactive({
    # Filter by Store.Name
    if (input$rep_filter != "All") {
      UnileverProd <- UnileverProd[UnileverProd$SALES.REP == input$rep_filter, ]
    }
    
    return(UnileverProd)
  })
  
  # Render data table
  output$UnileverProd <- DT::renderDataTable({
    DT::datatable(filtered_data(), options = list(pageLength = 10))
  })
      output$UnileverSales <- renderDT({
    UnileverSales 
  }, options = list(pageLength = 6, scrollX = TRUE,
                rownames = FALSE ))
        output$UnileverBeatrice <- renderDT({
    UnileverBeatrice 
  }, options = list(pageLength = 40, scrollX = TRUE,
                rownames = FALSE ))

         # Filtered data based on inputs
  filtered_data2 <- reactive({
    # Filter by Store.Name
    if (input$acc_filter != "All") {
      UnileverBeatrice <- UnileverBeatrice[UnileverBeatrice$SALES.REP == input$acc_filter, ]
    }
    
    return(UnileverBeatrice)
  })
  
  # Render data table
  output$UnileverBeatrice <- DT::renderDataTable({
    DT::datatable(filtered_data2(), options = list(pageLength = 10))
  })
        
     output$UnileverRegina<- renderDT({
    UnileverRegina 
  }, options = list(pageLength = 10, scrollX = TRUE,
                rownames = FALSE ))     
         output$UnileverWanyonyi<- renderDT({
    UnileverWanyonyi 
  }, options = list(pageLength = 10, scrollX = TRUE,
                rownames = FALSE ))     
        
        
}

shinyApp(ui, server)
```

