---
title: "R Notebook"
output: html_notebook
---

```{r}
# Group the data by month and sum the sales for each month
Walter_monthly <- Walter %>%
  mutate(month = floor_date(TRNS.DATE, "month")) %>%
  group_by(month) %>%
  summarize(Sales = sum(VALUE))

# convert month column to date format
Walter_monthly$month <- as.Date(paste0(Walter_monthly$month, "-01"))

# create xts time series object
Walter_monthlyts <- xts(Walter_monthly$Sales, order.by = Walter_monthly$month)

PlotWalter <- dygraph(Walter_monthlyts)%>%
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesOpts = list(strokeWidth = 3)) %>%
  dyOptions(colors = RColorBrewer::brewer.pal(8, "Dark2")) %>%
  dyLegend(show = "always") 

PlotWalter
```
```{r}
# Group the data by month and sum the sales for each month
Walter_monthly <- Walter %>%
  group_by(month = format(floor_date(TRNS.DATE, unit = "month"),"%Y-%m")) %>%
  summarise(Sales = sum(VALUE))  %>% arrange(desc(month))

#Creating an new column
Walter_total <-
Walter_monthly %>%  mutate(Targets = c(0,0,0,0,0,0,0,0,0,0,0)) %>% mutate(`Achievement % ` = ifelse((Targets = 0), 0,  paste0(round(Sales / Targets * 100), "%"))) %>%  arrange(desc(month))

Walter_total$Sales <- format(Walter_total$Sales, big.mark = ",", decimal.mark = ".", nsmall = 0)
```

```{r}
# Group the data by month and sum the sales for each month

Walter_brand <- Walter %>%
  group_by(month = format(floor_date(TRNS.DATE, unit = "month"),"%Y-%m"),BRAND) %>%
  summarise(Sales = sum(VALUE)) 

# Reshape the data from long to wide format
Walter_Brandwide <- dcast(Walter_brand, BRAND  ~  month, value.var = "Sales") %>% select(1,12,11,10,9,8,7) %>%  arrange(desc(`2023-06`))

Walter_Brandwide$`2023-06` <- format(Walter_Brandwide$`2023-06`, big.mark = ",", decimal.mark = ".", nsmall = 0)
Walter_Brandwide$`2023-05` <- format(Walter_Brandwide$`2023-05`, big.mark = ",", decimal.mark = ".", nsmall = 0)
Walter_Brandwide$`2023-04` <- format(Walter_Brandwide$`2023-04`, big.mark = ",", decimal.mark = ".", nsmall = 0)
Walter_Brandwide$`2023-03` <- format(Walter_Brandwide$`2023-03`, big.mark = ",", decimal.mark = ".", nsmall = 0)
Walter_Brandwide$`2023-02` <- format(Walter_Brandwide$`2023-02`, big.mark = ",", decimal.mark = ".", nsmall = 0)
Walter_Brandwide$`2023-01` <- format(Walter_Brandwide$`2023-01`, big.mark = ",", decimal.mark = ".", nsmall = 0)


```

